import os

#
# def parse_ac_file(file_path):
#     """
#     Parses a single AC analysis file and extracts complex voltage values.
#
#     Parameters:
#         file_path (str): Path to the input file.
#
#     Returns:
#         list: List of complex numbers representing the AC voltage values.
#     """
#     values = []
#
#     with open(file_path, 'r') as file:
#         for line in file:
#             line = line.strip()
#             if not line or line.startswith('*') or 'Index' in line or 'frequency' in line:
#                 continue  # Skip header/comment lines
#
#             parts = line.split()
#             if len(parts) < 4:
#                 continue
#
#             try:
#                 real_str = parts[2].replace(',', '')
#                 imag_str = parts[3]
#                 real = float(real_str)
#                 imag = float(imag_str)
#                 values.append(complex(real, imag))
#             except (ValueError, IndexError):
#                 continue  # Skip malformed lines
#
#     return values
#
#
# def parse_all_ac_files(vn_path="ac_vn.txt", vp_path="ac_vp.txt", vout_path="ac_out.txt"):
#     """
#     Parses all three AC files and returns a dictionary of complex values.
#
#     Parameters:
#         vn_path (str): Path to v(vn) data.
#         vp_path (str): Path to v(vp) data.
#         vout_path (str): Path to v(vout) data.
#
#     Returns:
#         dict: Dictionary containing lists of complex values for each signal.
#     """
#     results = {
#         "vn": [],
#         "vp": [],
#         "vout": []
#     }
#
#     if os.path.exists(vn_path):
#         results["vn"] = parse_ac_file(vn_path)
#     else:
#         print(f"File not found: {vn_path}")
#
#     if os.path.exists(vp_path):
#         results["vp"] = parse_ac_file(vp_path)
#     else:
#         print(f"File not found: {vp_path}")
#
#     if os.path.exists(vout_path):
#         results["vout"] = parse_ac_file(vout_path)
#     else:
#         print(f"File not found: {vout_path}")
#
#     return results
#
#
# if __name__ == "__main__":
#     # Parse the three AC files
#     ac_data = parse_all_ac_files()
#     print(ac_data)
#     # Output results
#     print(f"Extracted {len(ac_data['vn'])} V(Vn) values.")
#     print(f"Extracted {len(ac_data['vp'])} V(Vp) values.")
#     print(f"Extracted {len(ac_data['vout'])} V(Vout) values.")


# analysis.py
import os
import glob
import sys
import numpy as np


class FileParsingError(Exception):
    """Custom exception for errors during file parsing."""
    pass


class DcOpParser:
    """
    A parser for reading multi-column DC operating point files generated by ngspice.
    """

    @classmethod
    def parse(cls, file_path):
        """
        Parses a single DC op file. It reads the header to identify columns
        and returns a nested dictionary of the results.

        Example output: {'m1': {'id': 10e-6, 'vgs': 0.8, ...}, 'm2': {...}}
        """
        if not os.path.exists(file_path):
            print(f"Warning: DC operating point file not found: {file_path}")
            return {}

        with open(file_path, 'r') as f:
            lines = f.readlines()

        if len(lines) < 2:
            return {}  # Not enough data

        header = lines[0].strip().lower().split()
        values = lines[1].strip().split()

        results = {}
        for i, col_name in enumerate(header):
            try:
                # Check for transistor parameters like @m1[id]
                if '@m' in col_name and '[' in col_name:
                    # e.g., '@m1[id]' -> device='m1', param='id'
                    device, param = col_name.split('[')
                    device = device.replace('@', '')
                    param = param.replace(']', '')

                    if device not in results:
                        results[device] = {}
                    results[device][param] = float(values[i])
                else:
                    # Handle simple node voltages like v(vout)
                    results[col_name] = float(values[i])
            except (ValueError, IndexError):
                continue  # Skip columns that can't be parsed

        return results


class AcFileParser:
    """
    A class-based parser that automatically discovers and parses all
    'ac_*.txt' files in a given directory using a robust strategy.
    """

    @classmethod
    def parse(cls, directory_path="."):
        # This method remains the same.
        data = {}
        search_pattern = os.path.join(directory_path, "ac_*.txt")
        file_paths = glob.glob(search_pattern)

        if not file_paths:
            print(f"Warning: No files found matching pattern '{search_pattern}'")

        for file_path in file_paths:
            try:
                filename = os.path.basename(file_path)
                signal_name = os.path.splitext(filename)[0].replace('ac_', '')

                if not signal_name:
                    continue

                data[signal_name] = cls._process_file(file_path)
            except FileParsingError as e:
                print(f"Skipping incompatible file '{file_path}': {e}", file=sys.stderr)
                continue

        return data

    @classmethod
    def _process_file(cls, file_path):
        """
        Parses a single AC file by identifying data lines that start with a number.
        This method is now significantly more robust.
        """
        values = []
        with open(file_path, 'r') as file:
            for line_num, line in enumerate(file, 1):
                # .strip() removes leading/trailing whitespace including pagination chars
                line = line.strip()
                if not line:
                    continue

                # .split() handles any whitespace, including tabs
                parts = line.split()
                if not parts:
                    continue

                # --- ALLOW-LIST STRATEGY ---
                # A valid data line must start with a number (the index).
                # This check elegantly ignores all headers and separators.
                if not parts[0].isdigit():
                    continue

                # The rest of the logic is now protected by the check above.
                if len(parts) < 4:
                    continue  # Skip malformed data lines

                try:
                    real_str = parts[2].replace(',', '')
                    imag_str = parts[3]
                    values.append(complex(float(real_str), float(imag_str)))
                except (ValueError, IndexError):
                    # This is a final safeguard against unexpected data formats.
                    print(f"Warning: Skipping malformed numeric data on line {line_num} in {file_path}")
                    continue

        return values


if __name__ == "__main__":
    if len(sys.argv) > 1:
        target_directory = sys.argv[1]
    else:
        target_directory = "."
        print("No directory provided. Using current directory.")

    print(f"\n--- Parsing files in directory: '{os.path.abspath(target_directory)}' ---")

    ac_data = AcFileParser.parse(target_directory)

    print("\n--- Results ---")
    if ac_data:
        for signal, values in ac_data.items():
            print(f"Successfully extracted {len(values)} data points for signal '{signal}'.")
    else:
        print("No valid AC data was parsed.")